default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  host: postgres

development:
  <<: *default
  database: myapp_development
test:
  <<: *default
  database: myapp_test
